# cosmosproject_buybox:
#   outputs:
#     dev:
#       account: wrwycoj-fc44141
#       database: DAG_DB
#       password: Saaho123
#       role: ACCOUNTADMIN
#       schema: DEV
#       threads: 1
#       type: snowflake
#       user: Saaho
#       warehouse: COMPUTE_WH
#   target: dev


cosmosproject_buybox:
  outputs:
    outputs:
    dev:
      dataset: wellbefore
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/dbtproject-439612-b1aafa212fc0.json
      location: US
      method: service-account
      priority: interactive
      project: dbtproject-439612
      threads: 1
      type: bigquery
  target: dev

