# cosmosproject_buybox:
#   outputs:
#     dev:
#       account: jyvbwgv-llb12765
#       database: AIRFLOW
#       password: Sivateja#2003
#       role: ACCOUNTADMIN
#       schema: dev
#       threads: 1
#       type: snowflake
#       user: Sivateja2001
#       warehouse: COMPUTE_WH
#   target: dev


cosmosproject_buybox:
  outputs:
    dev:
      dataset: buybox_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      # keyfile: 'C:\Users\user\OneDrive - Sails Software Solutions Pvt Ltd\Documents\Git-Items\dbt-BigQuery-cosmos\buybox_dbt_snowflake\include\gcp\dbt-user-creds-02.json'
      keyfile: /usr/local/airflow/include/gcp/de-coe-creds-01.json
      location: US
      method: service-account
      priority: interactive
      project: de-coe
      threads: 1
      type: bigquery
  target: dev