cosmosproject_buybox:
  outputs:
    dev:
      account: jyvbwgv-llb12765
      database: AIRFLOW
      password: Sivateja#2003
      role: ACCOUNTADMIN
      schema: dev
      threads: 1
      type: snowflake
      user: Sivateja2001
      warehouse: COMPUTE_WH
  target: dev


# cosmosproject_buybox:
#   outputs:
#     dev:
#       dataset: buybox_dataset
#       job_execution_timeout_seconds: 300
#       job_retries: 1
#       keyfile: C:\Users\user\Downloads\BigQuery-keys\dbt-user-creds.json
#       location: US
#       method: service-account
#       priority: interactive
#       project: buybox-cloud-01
#       threads: 1
#       type: bigquery
#   target: dev